
#ifdef _WIN_
EXTERNAL WIN_OLECREATEOBJECT
#endif

EXTERNAL DRAWBARCODE
EXTERNAL TPY_PDFOPEN

EXTERNAL HB_JSONENCODE
EXTERNAL HB_JSONDECODE

EXTERNAL HB_RANDOMINT

EXTERNAL HB_STRTOUTF8

//EXTERNAL __VMXRELEASE
//EXTERNAL __MVRELEASE

#include "hbxlsxwriter_extern.ch"
